name: Java CI with Maven

on:
  schedule:
    - cron: '30 11 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      reason:
        description: 'Reason for the test run'
        required: false
        default: 'Automated Test Run'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
       

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn clean test -Dbrowser="chromeheadless"

      - name: Set up Git to use PAT
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git


      - name: Update dependency graph
        #uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        run: |
          # Add commands to update the dependency graph or any other build steps here.
          echo "Updating dependency graph or build process"
